In [1]:
import numpy as np

# Creating Arrays: 

In [2]:
arr1=np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [4]:
arr2=np.zeros(4)
arr2

array([0., 0., 0., 0.])

In [6]:
arr3=np.ones((4,5))
arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
arr4=np.arange(0,15,2)
arr4

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [14]:
arr5=np.linspace(2,10,20)
arr5

array([ 2.        ,  2.42105263,  2.84210526,  3.26315789,  3.68421053,
        4.10526316,  4.52631579,  4.94736842,  5.36842105,  5.78947368,
        6.21052632,  6.63157895,  7.05263158,  7.47368421,  7.89473684,
        8.31578947,  8.73684211,  9.15789474,  9.57894737, 10.        ])

# indexing and Slicing

In [33]:
arr=np.arange(0,12)
arr=arr.reshape((4,3))
arr[:1]

array([[0, 1, 2]])

# Flatten and Transpose

In [34]:
flatten=arr.flatten()
flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
arr.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

# Operations 

In [45]:
np.max(arr)
np.mean(arr)
arr*2


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]])