In [1]:
import numpy as np

In [2]:
np.__version__

'2.2.4'

# Creating Array

In [5]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## 0-D Array

In [6]:
arr1=np.array(10)
arr1

array(10)

## 1-D Array

In [8]:
arr1d=np.array([1,2,3,4])
arr1d
arr1d.shape

(4,)

## 2-D Array

In [10]:
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


## 3-D Array

In [17]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3d)
arr3d.shape
# arr3d.ndim

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [16]:
arr[0]+arr[4]


np.int64(6)

In [20]:
arr=arr3d.reshape(12)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [27]:
arr3d

(2, 2, 3)

In [28]:
x=np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [30]:
even=np.arange(0,25,2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [42]:
deff=np.arange(2,5.1,0.5)
deff

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [38]:
lin=np.linspace(0,20,num=8)
lin

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [107]:
import random
array=[]
array2=[]
for i in range(5):
    arr=random.randint(1,100)
    arr2=random.randint(1,100)
    array.append(arr)
    array2.append(arr2)
arr=np.array(array)
arr=np.sort(arr)
array2=np.sort(array2)
print(arr,array2)
a=np.sort(np.concatenate((arr,array2)))
print(a)


[30 37 42 64 68] [14 26 39 53 66]
[14 26 30 37 39 42 53 64 66 68]


In [111]:
a=a.reshape(5,2)
a.shape
a[a%2==0]

array([14, 26, 30, 42, 64, 66, 68])